spring.application.name=RopaStoreValidation

spring.datasource.url=jdbc:oracle:thin:@ropastorevalidation_high?TNS_ADMIN=C:/Projects/wallet/Wallet_RopaStoreValidation

spring.datasource.username=${DB_USER:ADMIN}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true